import fixtures from './fixtures.json'
import { ApiError } from '../shared/api/client'
import type { MatchResponse, Metadata, SearchParams } from '../shared/types/match'

// Generated by backend/scripts/export_fixtures.py and checked against Pydantic and TS.
export const mockMetadata: Metadata = fixtures.metadata

export function mockMatch(input: SearchParams): MatchResponse {
  const key = (query: SearchParams) => JSON.stringify([
    query.city, query.date, query.event_type, query.category, query.budget,
    query.language || null, query.duration ?? null,
  ])
  const fixture = fixtures.fixtures.find((item) => key(item.request) === key(input))
  if (!fixture) throw new ApiError('Для этих параметров нет dev-fixture. Выключите VITE_USE_MOCK_API для поиска по каталогу.', 422, 'fixture_not_found')
  return structuredClone(fixture.response) as MatchResponse
}
